/**
 * Generate the service worker after the Astro build.
 *
 * Why generated rather than hand-written in public/:
 *
 *  1. The cache version is derived from the built output, so every deploy that
 *     changes anything invalidates the old caches automatically. A hand-bumped
 *     `const VERSION = 'v2'` is bumped correctly right up until the once it is
 *     not, and that once strands every returning visitor on stale HTML.
 *  2. The precached shell is read from what was actually built, so it cannot
 *     list a route that no longer exists — an install-time 404 rejects the whole
 *     addAll() and silently leaves the visitor with no offline support at all.
 *  3. The origin layout lives in exactly one place. The previous build kept the
 *     base path in the config, the service worker, and the manifest, and relied
 *     on a human to keep three copies identical.
 *
 * Also emits sw-killswitch.js — see the note at the bottom.
 */
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';

const ROOT = path.resolve(import.meta.dirname, '..');
const DIST = path.join(ROOT, 'dist');

if (!existsSync(DIST)) {
  console.error('No dist/ — run `astro build` first.');
  process.exit(1);
}

/** Routes worth having before the connection drops. */
const SHELL_CANDIDATES = [
  '/index.html',
  '/map.html',
  '/categories.html',
  '/categories/index.html',
  '/about.html',
  '/offline.html',
  '/locations.json',
  '/manifest.webmanifest',
];

const toRoute = (file) =>
  file
    .replace(/\/index\.html$/, '/')
    .replace(/\.html$/, '')
    .replace(/^$/, '/');

const shell = [...new Set(SHELL_CANDIDATES.filter((f) => existsSync(path.join(DIST, f))).map(toRoute))];

// Version = hash of every built asset's name and size. Cheap, deterministic,
// and it changes whenever the output does.
const hash = createHash('sha256');
const walk = (dir) => {
  for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === 'pagefind') continue; // built after this script runs
      walk(p);
    } else {
      hash.update(`${path.relative(DIST, p)}:${statSync(p).size}`);
    }
  }
};
walk(DIST);
const VERSION = hash.digest('hex').slice(0, 12);

const sw = `/* PNW Historical Explorer service worker — GENERATED by scripts/build-sw.mjs.
 * Do not edit: rebuilding overwrites this file.
 * Build: ${VERSION}
 *
 * Strategy
 *   pages   network-first, falling back to cache, then /offline
 *   assets  stale-while-revalidate, capped
 *   tiles   stale-while-revalidate, capped, separate bucket
 *   audio   never auto-cached; served from the bucket the page fills on
 *           play or on an explicit "save for offline", with Range support
 */

const VERSION = '${VERSION}';
const SHELL_CACHE = 'pnw-shell-' + VERSION;
const RUNTIME_CACHE = 'pnw-runtime-' + VERSION;
/* Audio and tiles are versionless on purpose: they are large, they change
 * almost never, and a visitor who deliberately saved a narration should not
 * lose it because a CSS file changed. */
const AUDIO_CACHE = 'pnw-audio-v1';
const TILE_CACHE = 'pnw-tiles-v1';

const KEEP = [SHELL_CACHE, RUNTIME_CACHE, AUDIO_CACHE, TILE_CACHE];
const SHELL_URLS = ${JSON.stringify(shell)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(SHELL_CACHE)
      // Individual puts, not addAll(): one 404 must not reject the whole
      // install and leave the visitor with no offline support at all.
      .then((cache) => Promise.all(
        SHELL_URLS.map((url) =>
          fetch(url, { cache: 'reload' })
            .then((res) => (res.ok ? cache.put(url, res) : null))
            .catch(() => null)
        )
      ))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => !KEEP.includes(k)).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

async function trimCache(name, maxEntries) {
  const cache = await caches.open(name);
  const keys = await cache.keys();
  if (keys.length > maxEntries) {
    await cache.delete(keys[0]);
    return trimCache(name, maxEntries);
  }
}

/** Serve saved audio, honouring Range requests against the cached full body. */
async function audioResponse(request) {
  const cache = await caches.open(AUDIO_CACHE);
  const cached = await cache.match(request.url, { ignoreSearch: true });
  if (!cached) return fetch(request);

  const range = request.headers.get('range');
  if (!range) return cached.clone();

  const buf = await cached.clone().arrayBuffer();
  const total = buf.byteLength;
  const m = /bytes=(\\d+)-(\\d*)/.exec(range);
  const start = m ? parseInt(m[1], 10) : 0;
  const end = m && m[2] ? Math.min(parseInt(m[2], 10), total - 1) : total - 1;

  return new Response(buf.slice(start, end + 1), {
    status: 206,
    statusText: 'Partial Content',
    headers: {
      'Content-Type': cached.headers.get('Content-Type') || 'audio/mpeg',
      'Content-Range': 'bytes ' + start + '-' + end + '/' + total,
      'Content-Length': String(end - start + 1),
      'Accept-Ranges': 'bytes',
    },
  });
}

async function staleWhileRevalidate(request, cacheName, maxEntries) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  const network = fetch(request)
    .then((res) => {
      if (res.ok || res.type === 'opaque') {
        cache.put(request, res.clone());
        if (maxEntries) trimCache(cacheName, maxEntries);
      }
      return res;
    })
    .catch(() => null);
  return cached || (await network) || Response.error();
}

async function pageStrategy(request) {
  try {
    const res = await fetch(request);
    if (res.ok) {
      const cache = await caches.open(RUNTIME_CACHE);
      cache.put(request, res.clone());
      trimCache(RUNTIME_CACHE, 150);
    }
    return res;
  } catch {
    return (
      (await caches.match(request)) ||
      (await caches.match('/offline')) ||
      new Response('Offline', { status: 503, headers: { 'Content-Type': 'text/plain' } })
    );
  }
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);

  if (url.pathname.endsWith('.mp3')) {
    event.respondWith(audioResponse(request));
    return;
  }

  if (url.hostname.endsWith('tile.openstreetmap.org')) {
    event.respondWith(staleWhileRevalidate(request, TILE_CACHE, 400));
    return;
  }

  /* Media may be served from a separate origin (R2). Cache it like any other
   * asset rather than skipping it because the origin differs. */
  const sameOrigin = url.origin === location.origin;
  const isMedia = /\\.(png|jpe?g|webp|svg|gif|avif)$/i.test(url.pathname);
  if (!sameOrigin && !isMedia) return;

  if (request.mode === 'navigate') {
    event.respondWith(pageStrategy(request));
    return;
  }

  if (isMedia || /\\.(ico|js|css|woff2?|json|webmanifest)$/i.test(url.pathname) || url.pathname.startsWith('/_astro/')) {
    event.respondWith(staleWhileRevalidate(request, RUNTIME_CACHE, 300));
  }
});
`;

writeFileSync(path.join(DIST, 'sw.js'), sw, 'utf8');

/**
 * Kill switch for the OLD origin.
 *
 * A service worker registered at the previous GitHub Pages URL keeps serving
 * its cached copy of the site to anyone who ever visited, indefinitely, on an
 * origin nobody is deploying to any more. Those visitors are frozen on a dead
 * version and cannot be reached by anything published at the new address —
 * which is the single most damaging failure mode in this whole migration,
 * because it is completely invisible from the new site's analytics.
 *
 * Deploy this file to the legacy origin as its sw.js. It unregisters itself,
 * deletes every cache, and reloads open tabs, which then follow the redirect.
 */
const killswitch = `/* Legacy origin kill switch. Deploy as sw.js at the OLD address.
 * Unregisters the stale worker, clears its caches, reloads open tabs. */
self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.map((k) => caches.delete(k))))
      .then(() => self.registration.unregister())
      .then(() => self.clients.matchAll({ type: 'window' }))
      .then((clients) => clients.forEach((c) => c.navigate(c.url)))
  );
});
`;
writeFileSync(path.join(DIST, 'sw-killswitch.js'), killswitch, 'utf8');

console.log(`service worker: build ${VERSION}, ${shell.length} shell routes precached`);
console.log('               sw-killswitch.js also emitted (deploy to the legacy origin)');
